# Generated by Django 3.2.7 on 2021-12-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_auto_20211230_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
