# Generated by Django 3.2.4 on 2021-12-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_remove_order_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
