# Generated by Django 3.2.4 on 2022-01-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
