# Generated by Django 3.2.4 on 2022-01-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_auto_20220101_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
